name: Django-app workflow

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          # pip upgrade
          python -m pip install --upgrade pip
          # flake8 installation w plugins
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # dependencies installation
          
          cd infra_project/
          python manage.py test

          pip install -r requirements.txt

      - name: Test with flake8 and django tests
        run: |
          # project check w flake8
          python -m flake8
          cd infra_project/
          python manage.py test
